spring.application.name=crud-apirest

spring.datasource.url=jdbc:h2:file:./data/db_tareas
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD:}

#Para uso en MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/${DB_DATABASE}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}



#Para uso de H2
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


